=== ShimizuShiori/MockSql/schemas/task.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "DbType": {
            "type": "string",
            "enum": ["MSSQL"]
        },
        "RowCount": { "type": "number" },
        "TableName": { "type": "string" },
        "Generators": {
            "type": "array",
            "items": {
                "properties": {
                    "Name": { "type": "string" },
                    "Type": {
                        "type": "string",
                        "enum": ["String", "Int", "Boolean", "Datetime"]
                    },
                    "Inject": {
                        "oneOf": [
                            {
                                "type": "object",
                                "properties": {
                                    "MinLength": { "type": "number" },
                                    "MaxLength": { "type": "number" },
                                    "Type": {
                                        "type": "string",
                                        "enum": ["Enum", "Random"]
                                    },
                                    "Options": {
                                        "type": "array",
                                        "items": {
                                            "type": "string"
                                        }
                                    }
                                }
                            },
                            {
                                "type": "object",
                                "properties": {
                                    "RangeInfo": {
                                        "type": "object",
                                        "properties": {
                                            "Min": { "type": "number" },
                                            "Max": { "type": "number" },
                                            "Step": { "type": "number" }
                                        }
                                    },
                                    "Type": {
                                        "type": "string",
                                        "enum": ["Sequence", "Random"]
                                    },
                                    "SourceType": {
                                        "type": "string",
                                        "enum": ["Range", "List"]
                                    },
                                    "List": {
                                        "type": "array",
                                        "items": {
                                            "type": "number"
                                        }
                                    }
                                }
                            },
                            {
                                "type": "object",
                                "properties": {
                                    "Rate": {
                                        "type": "number"
                                    }
                                }
                            },
                            {
                                "type": "object",
                                "properties": {
                                    "MinData": { "type": "string" },
                                    "MaxDate": { "type": "string" }
                                }
                            }
                        ]
                    }
                }
            }
        },
        "Fields": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "Name": {
                        "type": "string"
                    },
                    "Type": {
                        "type": "string"
                    },
                    "GeneratorName": {
                        "type": "string"
                    }
                }
            }
        }
    }
}

=== ShimizuShiori/MockSql/schemas/demoTask.json
{
    "$schema": "./task.schema.json",
    "DbType": "MSSQL",
    "TableName": "TestTable",
    "Generators": [
        {
            "Name": "String10-100",
            "Type": "String",
            "Inject": {
                "MinLength": 10,
                "MaxLength": 100,
                "Type": "Random"
            }
        },
        {
            "Name": "Int1-4",
            "Type": "Int",
            "Inject": {
                "SourceType": "List",
                "Type": "Random",
                "List": [1, 2, 3, 4]
            }
        }
    ],
    "Fields": [
        {
            "Name": "Id",
            "Type": "int",
            "GeneratorName": "Int1-4"
        },
        {
            "Name": "Name",
            "Type": "varchar",
            "GeneratorName": "String10-100"
        }
    ]
}

=== ShimizuShiori/MockSql/Using/LES_ProductOrderRecord.Task.Json
{
    "Generators": [
        {
            "Name": "String_1_128",
            "Type": "String",
            "Inject": { "MinLength": 1, "MaxLength": 128, "Type": "Random" }
        },
        {
            "Name": "Int",
            "Type": "Int",
            "Inject": {
                "Type": "Random",
                "SourceType": "Range",
                "RangeInfo": { "Min": 0, "Max": 10000, "Step": 1 }
            }
        },
        {
            "Name": "Int",
            "Type": "Int",
            "Inject": {
                "Type": "Random",
                "SourceType": "Range",
                "RangeInfo": { "Min": 0, "Max": 10000, "Step": 1 }
            }
        },
        {
            "Name": "Datetime",
            "Type": "Datetime",
            "Inject": { "MinDate": "2000-01-01", "MaxDate": "2999-12-31" }
        },
        {
            "Name": "Datetime",
            "Type": "Datetime",
            "Inject": { "MinDate": "2000-01-01", "MaxDate": "2999-12-31" }
        },
        { "Name": "Boolean", "Type": "Boolean", "Inject": { "Rate": 50 } },
        { "Name": "Boolean", "Type": "Boolean", "Inject": { "Rate": 50 } }
    ],
    "Fields": [
        {
            "Name": "OrderId",
            "Type": "varchar",
            "GeneratorName": "String_1_128"
        },
        {
            "Name": "MaterialNumber",
            "Type": "varchar",
            "GeneratorName": "String_1_128"
        },
        {
            "Name": "SystemStatus",
            "Type": "varchar",
            "GeneratorName": "String_1_128"
        },
        {
            "Name": "MaterialDescription",
            "Type": "varchar",
            "GeneratorName": "String_1_128"
        },
        {
            "Name": "LastChangedBy",
            "Type": "varchar",
            "GeneratorName": "String_1_128"
        },
        { "Name": "Batch", "Type": "varchar", "GeneratorName": "String_1_128" },
        {
            "Name": "MRPArea",
            "Type": "varchar",
            "GeneratorName": "String_1_128"
        },
        {
            "Name": "PlannerGroup",
            "Type": "varchar",
            "GeneratorName": "String_1_128"
        },
        {
            "Name": "ProfitCenterg",
            "Type": "varchar",
            "GeneratorName": "String_1_128"
        },
        {
            "Name": "WBSElement",
            "Type": "varchar",
            "GeneratorName": "String_1_128"
        },
        {
            "Name": "StorageLocation",
            "Type": "varchar",
            "GeneratorName": "String_1_128"
        },
        {
            "Name": "ConfirmationNumber",
            "Type": "varchar",
            "GeneratorName": "String_1_128"
        },
        {
            "Name": "BaseUnitofMeasure",
            "Type": "varchar",
            "GeneratorName": "String_1_128"
        },
        {
            "Name": "OrderType",
            "Type": "varchar",
            "GeneratorName": "String_1_128"
        },
        {
            "Name": "MRPController",
            "Type": "varchar",
            "GeneratorName": "String_1_128"
        },
        {
            "Name": "ProdnSupervisor",
            "Type": "varchar",
            "GeneratorName": "String_1_128"
        },
        { "Name": "Plant", "Type": "varchar", "GeneratorName": "String_1_128" },
        {
            "Name": "UnitOfMeasure",
            "Type": "varchar",
            "GeneratorName": "String_1_128"
        },
        {
            "Name": "ProductionVersion",
            "Type": "varchar",
            "GeneratorName": "String_1_128"
        },
        {
            "Name": "CustomerPONumber",
            "Type": "varchar",
            "GeneratorName": "String_1_128"
        },
        {
            "Name": "MESRouting",
            "Type": "varchar",
            "GeneratorName": "String_1_128"
        },
        {
            "Name": "Priority",
            "Type": "varchar",
            "GeneratorName": "String_1_128"
        },
        {
            "Name": "SalesOrder",
            "Type": "varchar",
            "GeneratorName": "String_1_128"
        },
        {
            "Name": "SpecialStock",
            "Type": "varchar",
            "GeneratorName": "String_1_128"
        },
        { "Name": "OrderQuantity", "Type": "int", "GeneratorName": "Int" },
        { "Name": "TotalScrap", "Type": "int", "GeneratorName": "Int" },
        { "Name": "DeliveredQuantity", "Type": "int", "GeneratorName": "Int" },
        { "Name": "InspectionLot", "Type": "int", "GeneratorName": "Int" },
        { "Name": "SalesOrderItem", "Type": "int", "GeneratorName": "Int" },
        {
            "Name": "SchedFloatAfterProd",
            "Type": "float",
            "GeneratorName": "Int"
        },
        {
            "Name": "SchedFloatBeforeProd",
            "Type": "float",
            "GeneratorName": "Int"
        },
        { "Name": "ManagedInfo_ID", "Type": "int", "GeneratorName": "Int" },
        {
            "Name": "BasicStartDate",
            "Type": "datetime",
            "GeneratorName": "Datetime"
        },
        {
            "Name": "BasicFinishDate",
            "Type": "datetime",
            "GeneratorName": "Datetime"
        },
        {
            "Name": "ActualStartTime",
            "Type": "datetime",
            "GeneratorName": "Datetime"
        },
        {
            "Name": "ActualFinishDate",
            "Type": "datetime",
            "GeneratorName": "Datetime"
        },
        {
            "Name": "ChangeDate",
            "Type": "datetime",
            "GeneratorName": "Datetime"
        },
        {
            "Name": "CreatedOn",
            "Type": "datetime",
            "GeneratorName": "Datetime"
        },
        {
            "Name": "ReleaseDate",
            "Type": "datetime",
            "GeneratorName": "Datetime"
        },
        {
            "Name": "ConfirmedFinishDate",
            "Type": "datetime",
            "GeneratorName": "Datetime"
        },
        { "Name": "Start", "Type": "datetime", "GeneratorName": "Datetime" },
        {
            "Name": "RequiredDeliveryDate",
            "Type": "datetime",
            "GeneratorName": "Datetime"
        },
        { "Name": "Deletion", "Type": "bit", "GeneratorName": "Boolean" }
    ],
    "TableName": "",
    "DbType": "MSSQL",
    "RowCount": 100,
    "$schema": "./task.schema.json"
}
